# Generated by Django 4.0.1 on 2022-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skycards_api', '0002_card_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_url',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
