# Generated by Django 3.2.9 on 2022-01-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skycards_api', '0003_alter_card_card_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
